### ISSUE TITLE
Week 1 Checklist

### ISSUE THREAD

**Issue by LindaLiu1202** [TianbinLiu/CSA-FinalProject#6]
## Project Description
The purpose of our project is to help students gain computer science knowledge in a fun and engaging way. The main character (user) would have conversations with all students in the classroom -> battle with them and gain knowledge on each cb unit. After talking with all students, user would enter the final battle with Mr M... Would you succeed the battle?

## Design
- [ ] homepage background 

## Menu
- [ ] option buttons
- [ ] exit
- [ ] music
- [ ] animation

## Homepage (classroom)
- [ ] environment setup
  - still need to find suitable background and characters
- [ ] character sprite (animation)
- [ ] user control
- [ ] adding game objects (javascript class objects)
- [ ] character movement

## Dialogue with Students
- [ ] story/dialogue script
- [ ] background
- [ ] character
- [ ] dialogue box
- [ ] answer options

## FInal Battle with Mr M
- [ ] questions from all cb units
- [ ] card game
  - environment (background, music)
  - cards with random answer options
  - drag and drop function
